name: unbeliever
version: 0.3.1
synopsis: Opinionated Haskell Interoperability
description: |
  A library to help build command-line programs, both tools and
  longer-running daemons.
stability: experimental
license: BSD3
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2018 Operational Dynamics Consulting Pty Ltd, and Others
tested-with: GHC == 8.4

dependencies:
 - aeson
 - async
 - base
 - bytestring
 - chronologique
 - deepseq
 - exceptions
 - fingertree
 - hashable
 - heredoc
 - hourglass
 - mtl
 - prettyprinter
 - prettyprinter-ansi-terminal
 - safe-exceptions
 - scientific
 - stm
 - terminal-size
 - text
 - text-short
 - transformers
 - unordered-containers
 - unix
 - vector

library:
  source-dirs: lib
  exposed-modules:
   - Core.Text
   - Core.Text.Bytes
   - Core.Text.Rope
   - Core.Text.Utilities
   - Core.Encoding
   - Core.Encoding.Json
   - Core.System
   - Core.System.Base
   - Core.System.External
   - Core.Program
   - Core.Program.Arguments
   - Core.Program.Execute
   - Core.Program.Logging
  other-modules:
   - Core.Program.Context
   - Core.Program.Signal

executables:
  experiment:
    dependencies:
     - unbeliever
   
    ghc-options: -threaded -Wall -Wwarn -fwarn-tabs
   
    source-dirs: tests
    main: SimpleExperiment.hs
    other-modules: []

    ghc-prof-options: -fprof-auto

tests:
  check:
    dependencies:
     - hspec
     - unbeliever

    ghc-options: -threaded -Wall -Wwarn -fwarn-tabs

    source-dirs:
     - tests
    main: TestSuite.hs
    other-modules:
     - CheckRopeBehaviour
     - CheckJsonWrapper
     - CheckArgumentsParsing
     - CheckProgramMonad

benchmarks:
  performance:
    dependencies:
     - gauge
     - unbeliever

    ghc-options: -threaded -Wall -Wwarn -fwarn-tabs

    source-dirs:
     - bench
    main: GeneralPerformance.hs
    other-modules: []

