name: unbeliever
version: 0.8.3.0
synopsis: Opinionated Haskell Interoperability
description: |
  A library to help build command-line programs, both tools and
  longer-running daemons.

  A description of this package, a list of features, and some background
  to its design is contained in the
  <https://github.com/oprdyn/unbeliever/blob/master/README.markdown README>
  on GitHub.
  
  Useful starting points in the documentation are "Core.Program.Execute"
  and "Core.Text.Rope".

stability: experimental
license: BSD3
license-file: LICENCE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2018-2019 Operational Dynamics Consulting Pty Ltd, and Others
tested-with: GHC == 8.6
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: oprdyn/unbeliever

flags:
  development:
    manual: true
    default: false

dependencies:
 - aeson
 - async
 - base >= 4.11 && < 5
 - bytestring
 - Cabal
 - chronologique
 - containers
 - deepseq
 - directory
 - exceptions
 - fingertree
 - hashable
 - hourglass
 - mtl
 - prettyprinter
 - prettyprinter-ansi-terminal
 - safe-exceptions
 - scientific
 - stm
 - template-haskell
 - terminal-size
 - text
 - text-short
 - transformers
 - unordered-containers
 - unix
 - vector

library:
  source-dirs: lib
  exposed-modules:
   - Core.Data
   - Core.Data.Structures
   - Core.Encoding
   - Core.Encoding.Json
   - Core.Program
   - Core.Program.Arguments
   - Core.Program.Execute
   - Core.Program.Logging
   - Core.Program.Metadata
   - Core.Program.Unlift
   - Core.Text
   - Core.Text.Bytes
   - Core.Text.Rope
   - Core.Text.Utilities
   - Core.System
   - Core.System.Base
   - Core.System.External
  other-modules:
   - Core.Program.Context
   - Core.Program.Signal


tests:
  check:
    dependencies:
     - hspec
     - unbeliever
    ghc-options: -threaded
    source-dirs:
     - tests
    main: TestSuite.hs
    other-modules:
     - CheckArgumentsParsing
     - CheckBytesBehaviour
     - CheckContainerBehaviour
     - CheckJsonWrapper
     - CheckProgramMonad
     - CheckRopeBehaviour

  experiment:
    when:
      - condition: flag(development)
        then:
          buildable: true
          ghc-prof-options: -fprof-auto-top
        else:
          buildable: false
    dependencies:
     - unbeliever
    ghc-options: -threaded
    source-dirs: tests
    main: SimpleExperiment.hs
    other-modules: []

  snippet:
    when:
      - condition: flag(development)
        then:
          buildable: true
          ghc-prof-options: -fprof-auto-top
        else:
          buildable: false
    dependencies:
     - unbeliever
    ghc-options: -threaded
    source-dirs: tests
    main: Snippet.hs
    other-modules: []

benchmarks:
  performance:
    dependencies:
     - gauge
     - unbeliever
    ghc-options: -threaded
    source-dirs:
     - bench
    main: GeneralPerformance.hs
    other-modules: []

