name: unbeliever
version: 0.0.2
description: Opinionated Haskell Interoperability
license: BSD3
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2018 Operational Dynamics Consulting Pty Ltd, and Others
tested-with: GHC == 8.4

dependencies:
 - aeson
 - async
 - base
 - bytestring
 - chronologique
 - exceptions
 - hashable
 - hourglass
 - mtl
 - prettyprinter
 - prettyprinter-ansi-terminal
 - safe-exceptions
 - scientific
 - stm
 - text
 - transformers
 - unordered-containers
 - vector

library:
  source-dirs: lib
  exposed-modules:
   - Core.Text
   - Core.Json
   - Core.Program
   - Core.System
   - Core.Render
  other-modules:
   - Core.Logging

executables:
  experiment:
    dependencies:
     - unbeliever
   
    ghc-options: -threaded -Wall -Wwarn -fwarn-tabs
   
    source-dirs: tests
    main: Experiment.hs
                      
