name: unbeliever
version: 0.9.4.2
synopsis: Opinionated Haskell Interoperability
description: |
  A library to help build command-line programs, both tools and
  longer-running daemons.

  A description of this package, a list of features, and some background
  to its design is contained in the
  <https://github.com/oprdyn/unbeliever/blob/master/README.markdown README>
  on GitHub.
  
  Useful starting points in the documentation are "Core.Program.Execute"
  and "Core.Text.Rope".

stability: experimental
license: BSD3
license-file: LICENCE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2018-2019 Operational Dynamics Consulting Pty Ltd, and Others
tested-with: GHC == 8.6.4
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: oprdyn/unbeliever

dependencies:
 - base >= 4.11 && < 5
 - core-system
 - core-text
 - core-program

library:
  source-dirs: lib
  exposed-modules:
   - Core
  other-modules: []

tests:
  check:
    dependencies:
     - bytestring
     - fingertree
     - hspec
     - safe-exceptions
     - text
     - text-short
     - unbeliever
    ghc-options: -threaded
    source-dirs:
     - tests
    main: TestSuite.hs
    other-modules:
     - CheckArgumentsParsing
     - CheckBytesBehaviour
     - CheckContainerBehaviour
     - CheckJsonWrapper
     - CheckProgramMonad
     - CheckRopeBehaviour

benchmarks:
  performance:
    dependencies:
     - gauge
     - unbeliever
    ghc-options: -threaded
    source-dirs:
     - bench
    main: GeneralPerformance.hs
    other-modules: []
