name: core-program
version: 0.2.4.1
synopsis: Opinionated Haskell Interoperability
description: |
  A library to help build command-line programs, both tools and
  longer-running daemons.
  
  A description of this package, a list of features, and some background
  to its design is contained in the
  <https://github.com/oprdyn/unbeliever/blob/master/README.markdown README>
  on GitHub.
  
  See "Core.Program.Execute" to get started.

stability: experimental
license: BSD3
license-file: LICENSE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2018-2019 Operational Dynamics Consulting Pty Ltd, and Others
tested-with: GHC == 8.6.5
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: oprdyn/unbeliever

dependencies:
 - base >= 4.11 && < 5
 - bytestring
 - hashable >= 1.2 && < 1.4
 - prettyprinter >= 1.2.1.1 && < 1.7
 - prettyprinter-ansi-terminal
 - template-haskell >= 2.14 && < 3
 - text
 - text-short

library:
  dependencies:
   - async
   - core-text >= 0.2.2
   - core-data
   - chronologique
   - directory
   - exceptions
   - filepath
   - fsnotify
   - hourglass
   - mtl
   - safe-exceptions
   - stm
   - terminal-size
   - transformers
   - unix
  source-dirs: lib
  exposed-modules:
   - Core.Program
   - Core.Program.Arguments
   - Core.Program.Execute
   - Core.Program.Logging
   - Core.Program.Metadata
   - Core.Program.Notify
   - Core.Program.Unlift
   - Core.System
   - Core.System.Base
   - Core.System.External
   - Core.System.Pretty
  other-modules:
   - Core.Program.Context
   - Core.Program.Signal
