name: core-data
version: 0.2.0.0
synopsis: Opinionated Haskell Interoperability
description: |
  A library to help build command-line programs, both tools and
  longer-running daemons.

  A description of this package, a list of features, and some background
  to its design is contained in the
  <https://github.com/oprdyn/unbeliever/blob/master/README.markdown README>
  on GitHub.
  
  Useful starting points in the documentation are "Core.Program.Execute"
  and "Core.Text.Rope".

stability: experimental
license: BSD3
license-file: ../LICENCE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2018-2019 Operational Dynamics Consulting Pty Ltd, and Others
tested-with: GHC == 8.6.5
category: System
ghc-options: -Wall -Wwarn -fwarn-tabs
github: oprdyn/unbeliever

dependencies:
 - aeson
 - base >= 4.11 && < 5
 - bytestring
 - containers
 - hashable
 - prettyprinter
 - prettyprinter-ansi-terminal
 - scientific
 - text
 - unordered-containers
 - vector
 - core-text

library:
  source-dirs: lib
  exposed-modules:
   - Core.Data
   - Core.Data.Structures
   - Core.Encoding
   - Core.Encoding.Json
  other-modules: []

